Solution/TW.MyBlog.Web.Admin/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TW.MyBlog.Application.Service.Interface;
using TW.MyBlog.Domain.Base;
using TW.MyBlog.Domain.Model;
using TW.MyBlog.Domain.Model.DTO;
using TW.MyBlog.Infrastructure.Common;
using TW.MyBlog.Web.Admin.Areas.Admin.Lib;
using TW.MyBlog.Web.Admin.Lib;
using TW.MyBlog.Web.Areas.Admin.Attrbute;
using TW.Utility;

namespace TW.MyBlog.Web.Admin.Areas.Admin.Controllers
{
    /// <summary>
    /// 博文信息相关
    /// </summary>
    [FormHandle]
    public class PostController : BaseController
    {
        private readonly IMyBlog_Post_PostInfoServices _postinfoServices;
        private readonly IMyBlog_Post_PostCategoryServices _postcategoryServices;
        private readonly ILocalCommon _localCommon;
        public PostController(ILocalCommon localCommon, IMyBlog_Post_PostInfoServices postinfoServices, IMyBlog_Post_PostCategoryServices postcategoryServices) : base(localCommon)
        {
            _postinfoServices = postinfoServices;
            _localCommon = localCommon;
            _postcategoryServices = postcategoryServices;
        }

        #region Public
        public async Task<IActionResult> GetPostCategory(string value, bool isEmpty = false)
        {
            return Json(SelectListItemHelper.GetListByT(
                (await _postcategoryServices.GetManyAsync(
                    new DirectSpecification<MyBlog_Post_PostCategory>(x => !x.IsDeleted))).Select(x => new SelectListItem()
                    {
                        Text = x.CategoryNAme,
                        Value = x.ID.ToString(),
                        Selected = value != null && (value == x.ID.ToString())
                    }), isEmpty));
        }


        #endregion

        #region PostInfo管理
        public IActionResult PostInfo()
        {
            ViewBag.ColumsTitle = _localCommon.GetColumsName<PostPostInfoDTO>();
            ViewBag.DataUrl = "/Admin/Post/GetPostInfoList";
            return View();
        }
        public IActionResult AddPostInfo()
        {
            return View("PostInfoDetail", new MyBlog_Post_PostInfo());
        }

        public async Task<IActionResult> EditPostInfo(Guid Id)
        {
            return View("PostInfoDetail", await _postinfoServices.GetByKeyAsync(Id));
        }

        [HttpPost]
        [SubAuth(nameof(AddPostInfo), nameof(EditPostInfo))]
        public async Task<IActionResult> SavePostInfo(MyBlog_Post_PostInfo model)
        {
            var oldid = model.ID;
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                x.Success = true;
                await _postinfoServices.ModifyModel(model);
                x.Message = "" + (oldid == Guid.Empty ? "添加" : "编辑") + "成功!";
            });
            return Json(result);
        }

        [SubAuth(nameof(PostInfo), nameof(ExportPostInfo))]
        public async Task<IActionResult> GetPostInfoList(int page, int rows, string sidx, string sord, string exportTitles, bool export = false)
        {
            var sort = !string.IsNullOrEmpty(sidx) ? new Dictionary<string, string>() { { sidx, sord.ToUpper() } } : new Dictionary<string, string>() { { "CreateTime", "DESC" } };
            if (!export)
            {
                return Json(GetRowToGrid((await _postinfoServices.GetPostInfoList(page, rows, sort, export))));
            }
            else
            {
                var fileName = "导出PostInfo管理";
                var titles = exportTitles.Split(',').ToList();
                var record = (await _postinfoServices.GetPostInfoList(page, rows, sort, export)).Data;
                return File(ReturnFile(fileName, titles, record), "application/vnd.ms-excel");
            }
        }
        public async Task<IActionResult> DelPostInfo(string ids)
        {
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                if (ids.Split(',').Any())
                {
                    var delId = ids.Split(',').Select(Guid.Parse);
                    await _postinfoServices.DelModelsById(delId);
                    x.Success = true;
                    x.Message = "删除成功!";
                }
            });
            return Json(result);
        }
        public ActionResult ExportPostInfo()
        {
            //ViewBag.ColumsTitle = _localCommon.GetExportColumsName<PostPostInfoDTO>();
            ViewBag.SeaechCondition = Request.QueryString.Value?.ToString();
            ViewBag.DataUrl = "/Admin/Post/GetPostInfoList";
            return View("~/Areas/Admin/Views/Home/ExportRecord.cshtml");
        }
        #endregion

        #region PostCategory管理
        public IActionResult PostCategory()
        {
            ViewBag.ColumsTitle = _localCommon.GetColumsName<PostPostCategoryDTO>();
            ViewBag.DataUrl = "/Admin/Post/GetPostCategoryList";
            return View();
        }
        public IActionResult AddPostCategory()
        {
            return View("PostCategoryDetail", new MyBlog_Post_PostCategory());
        }

        public async Task<IActionResult> EditPostCategory(Guid Id)
        {
            return View("PostCategoryDetail", await _postcategoryServices.GetByKeyAsync(Id));
        }

        [HttpPost]
        [SubAuth(nameof(AddPostCategory), nameof(EditPostCategory))]
        public async Task<IActionResult> SavePostCategory(MyBlog_Post_PostCategory model)
        {
            var oldid = model.ID;
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                x.Success = true;
                await _postcategoryServices.ModifyModel(model);
                x.Message = "" + (oldid == Guid.Empty ? "添加" : "编辑") + "成功!";
            });
            return Json(result);
        }

        [SubAuth(nameof(PostCategory), nameof(ExportPostCategory))]
        public async Task<ActionResult> GetPostCategoryList(int page, int rows, string sidx, string sord, string exportTitles, bool export = false)
        {
            var sort = !string.IsNullOrEmpty(sidx) ? new Dictionary<string, string>() { { sidx, sord.ToUpper() } } : new Dictionary<string, string>() { { "CreateTime", "DESC" } };
            if (!export)
            {
                return Json(GetRowToGrid((await _postcategoryServices.GetPostCategoryList(page, rows, sort, export))));
            }
            else
            {
                var fileName = "导出PostCategory管理";
                var titles = exportTitles.Split(',').ToList();
                var record = (await _postcategoryServices.GetPostCategoryList(page, rows, sort, export)).Data;
                return File(ReturnFile(fileName, titles, record), "application/vnd.ms-excel");
            }
        }
        public async Task<ActionResult> DelPostCategory(string ids)
        {
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                if (ids.Split(',').Any())
                {
                    var delId = ids.Split(',').Select(Guid.Parse);
                    await _postcategoryServices.DelModelsById(delId);
                    x.Success = true;
                    x.Message = "删除成功!";
                }
            });
            return Json(result);
        }
        public ActionResult ExportPostCategory()
        {
            ViewBag.ColumsTitle = _localCommon.GetExportColumsName<PostPostCategoryDTO>();
            ViewBag.SeaechCondition = Request.QueryString.Value?.ToString();
            ViewBag.DataUrl = "/Admin/Post/GetPostCategoryList";
            return View("~/Areas/Admin/Views/Home/ExportRecord.cshtml");
        }
        #endregion
    }
}

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Controllers/ViewComponents/ModuleActionBtnViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TW.MyBlog.Web.Admin.Areas.Admin.Lib;
using Microsoft.AspNetCore.Mvc;

namespace TW.MyBlog.Web.Admin.Areas.Admin
{
    public class ModuleActionBtnViewComponent : ViewComponent
    {
        private readonly ILocalCommon _localCommon;
        public ModuleActionBtnViewComponent(ILocalCommon localCommon)
        {
            _localCommon = localCommon;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("/Areas/Admin/Views/Shared/ViewComponents/ModuleActionBtn/Default.cshtml", await _localCommon.CurrentFullUserAsync());
        }
    }
}

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Views/Post/EditPostInfo.cshtml
vvxc

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Views/Post/PostCategory.cshtml
@{
    ViewBag.Title = "博文分类管理";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Js{
    <script src="/Areas/Admin/js/Post/PostCategory.js"></script>
}
<script>
    var colModel = [
       { name: 'id', index: 'id', hidden: true },
{ id: 'EditOpt', name: '', index: 'id', width: 35, align: 'center', fixed: true, sortable: false, resize: false, formatter: editIcon },
{ label: '分类名称', name: 'CategoryNAme', index: 'CategoryNAme' },
{ label: 'FId', name: 'FId', index: 'FId' },
{ label: '创建时间', name: 'CreateTime', index: 'CreateTime' },

    ]
</script>
<div class="row">
    <div class="col-xs-12">
        <form id="SearchForm">
            <div class="ui-filter clearfix">
                    <!--在此处添加客户代码-->
					@*<input type="hidden" name="HiddenInput"/>隐藏域查询
                        <div class="btn-group search-group">
                            <label class="control-label ">下拉列表查询</label>
                            <select style="width: 100px;" id="searchdroplist" name="searchdroplist" ajax-url="/Admin/xxx"></select>
                        </div>
                        <div class="btn-group search-group">
                            <label class="control-label">所在省市区查询</label>
                            <select style="width: 100px;" id="searchProvinceId" name="searchProvinceId" class="listprovinceId"></select>
                            <select style="width: 100px;" id="searchCityId" name="searchCityId" class="listcityId"></select>
                            <select style="width: 100px;" id="searchDistrictId" name="searchDistrictId"></select>
                        </div>
                        <div class="btn-group search-group">
                            <label class="control-label">日期查询</label>
                            <input style="width: 100px;" type="text" id="StartDate" name="StartDate" />-
                            <input style="width: 100px;" type="text" id="EndDate" name="EndDate" />
                        </div>
                        <div class="btn-group search-group">
                            <label class="control-label">文本框查询</label>
                            <select class="input-medium" id="searchMemberType" name="searchMemberType" style="width: 100px;">
                                @Html.Raw(ZMDTech.Utility.EnumHelper.EnumTypeGetOption<查询枚举>(false))                               
                            </select>
                            <input style="width: 110px;" type="text" id="searchText" name="searchText" placeholder="请输入搜索内容"/>
                            <!--客户代码结束-->
                            <button id="btnSearch" class="btn btn-info btn-lg btn-white ui-btn-search" type="button">
                                <i class="ace-icon fa fa-search bigger-110"></i>
                                查询
                            </button>
                        </div>*@
            </div>
            @await Component.InvokeAsync("ModuleActionBtn")
        </form>
        @Html.Partial("~/Areas/Admin/Views/Shared/_GeneralGrid.cshtml")
    </div>
</div>

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Views/Post/PostCategoryDetail.cshtml
@using TW.MyBlog.Domain.Model
@model MyBlog_Post_PostCategory
@Html.HiddenFor(x => x.ID)
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>分类名称</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="CategoryNAme" name="CategoryNAme" required value="@Model.CategoryNAme" maxlength="10" placeholder="请输入分类名称" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<script src="/Areas/Admin/js/Post/PostCategoryDetail.js"></script>

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Views/Post/PostComment.cshtml
@{
    ViewBag.Title = "PostComment管理";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Js{
    <script src="/Areas/Admin/js/Post/PostComment.js"></script>
}
<script>
    var colModel = [
       { name: 'id', index: 'id', hidden: true },
{ id: 'EditOpt', name: '', index: 'id', width: 35, align: 'center', fixed: true, sortable: false, resize: false, formatter: editIcon },
{ label: '文章编号', name: 'PostId', index: 'PostId' },
{ label: '评论编号', name: 'CommentId', index: 'CommentId' },
{ label: '内容', name: 'Comment', index: 'Comment' },
{ label: '评论人', name: 'UserId', index: 'UserId' },
{ label: 'IP', name: 'CommentIp', index: 'CommentIp' },
{ label: '创建时间', name: 'CreateTime', index: 'CreateTime' },

    ]
</script>
<div class="row">
    <div class="col-xs-12">
        <form id="SearchForm">
            <div class="ui-filter clearfix">
                    <!--在此处添加客户代码-->
					@*<input type="hidden" name="HiddenInput"/>隐藏域查询
                        <div class="btn-group search-group">
                            <label class="control-label ">下拉列表查询</label>
                            <select style="width: 100px;" id="searchdroplist" name="searchdroplist" ajax-url="/Admin/xxx"></select>
                        </div>
                        <div class="btn-group search-group">
                            <label class="control-label">所在省市区查询</label>
                            <select style="width: 100px;" id="searchProvinceId" name="searchProvinceId" class="listprovinceId"></select>
                            <select style="width: 100px;" id="searchCityId" name="searchCityId" class="listcityId"></select>
                            <select style="width: 100px;" id="searchDistrictId" name="searchDistrictId"></select>
                        </div>
                        <div class="btn-group search-group">
                            <label class="control-label">日期查询</label>
                            <input style="width: 100px;" type="text" id="StartDate" name="StartDate" />-
                            <input style="width: 100px;" type="text" id="EndDate" name="EndDate" />
                        </div>
                        <div class="btn-group search-group">
                            <label class="control-label">文本框查询</label>
                            <select class="input-medium" id="searchMemberType" name="searchMemberType" style="width: 100px;">
                                @Html.Raw(ZMDTech.Utility.EnumHelper.EnumTypeGetOption<查询枚举>(false))                               
                            </select>
                            <input style="width: 110px;" type="text" id="searchText" name="searchText" placeholder="请输入搜索内容"/>
                            <!--客户代码结束-->
                            <button id="btnSearch" class="btn btn-info btn-lg btn-white ui-btn-search" type="button">
                                <i class="ace-icon fa fa-search bigger-110"></i>
                                查询
                            </button>
                        </div>*@
            </div>
            @await Component.InvokeAsync("ModuleActionBtn")
        </form>
        @Html.Partial("~/Areas/Admin/Views/Shared/_GeneralGrid.cshtml")
    </div>
</div>

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Views/Post/PostCommentDetail.cshtml
@using TW.MyBlog.Domain.Model
@model MyBlog_Post_PostComment
@Html.HiddenFor(x=>x.ID)
@Html.AntiForgeryToken()
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">文章编号</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="PostId" name="PostId" ajax-url="/Admin/Post/获取特定列表">@*TODO:请改写为对应的ajax请求*@</select>        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">评论编号</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="CommentId" name="CommentId" ajax-url="/Admin/Post/获取特定列表">@*TODO:请改写为对应的ajax请求*@</select>        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>内容</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type = "text" id="Comment" name="Comment" required value="@Model.Comment" maxlength="0" placeholder="请输入内容" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">评论人</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="UserId" name="UserId" ajax-url="/Admin/Post/获取特定列表">@*TODO:请改写为对应的ajax请求*@</select>        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>IP</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type = "text" id="CommentIp" name="CommentIp" required value="@Model.CommentIp" maxlength="100" placeholder="请输入IP" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>

 <script src="/Areas/Admin/js/Post/PostCommentDetail.js"></script>

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Views/Post/PostInfo.cshtml
@{
    ViewBag.Title = "博文发布管理";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Js{
    <script src="/Areas/Admin/js/Post/PostInfo.js"></script>
}
<div class="row">
    <div class="col-xs-12">
        <form id="SearchForm">
            <div class="ui-filter clearfix">
                <!--在此处添加客户代码-->
                @*<input type="hidden" name="HiddenInput"/>隐藏域查询
                    <div class="btn-group search-group">
                        <label class="control-label ">下拉列表查询</label>
                        <select style="width: 100px;" id="searchdroplist" name="searchdroplist" ajax-url="/Admin/xxx"></select>
                    </div>
                    <div class="btn-group search-group">
                        <label class="control-label">所在省市区查询</label>
                        <select style="width: 100px;" id="searchProvinceId" name="searchProvinceId" class="listprovinceId"></select>
                        <select style="width: 100px;" id="searchCityId" name="searchCityId" class="listcityId"></select>
                        <select style="width: 100px;" id="searchDistrictId" name="searchDistrictId"></select>
                    </div>
                    <div class="btn-group search-group">
                        <label class="control-label">日期查询</label>
                        <input style="width: 100px;" type="text" id="StartDate" name="StartDate" />-
                        <input style="width: 100px;" type="text" id="EndDate" name="EndDate" />
                    </div>
                    <div class="btn-group search-group">
                        <label class="control-label">文本框查询</label>
                        <select class="input-medium" id="searchMemberType" name="searchMemberType" style="width: 100px;">
                            @Html.Raw(ZMDTech.Utility.EnumHelper.EnumTypeGetOption<查询枚举>(false))
                        </select>
                        <input style="width: 110px;" type="text" id="searchText" name="searchText" placeholder="请输入搜索内容"/>
                        <!--客户代码结束-->
                        <button id="btnSearch" class="btn btn-info btn-lg btn-white ui-btn-search" type="button">
                            <i class="ace-icon fa fa-search bigger-110"></i>
                            查询
                        </button>
                    </div>*@
            </div>
            @await Component.InvokeAsync("ModuleActionBtn")
        </form>
        @Html.Partial("~/Areas/Admin/Views/Shared/_GeneralGrid.cshtml")
    </div>
</div>

Solution/TW.MyBlog.Web.Admin/Areas/Admin/Views/Post/PostInfoDetail.cshtml
@using TW.MyBlog.Domain.Model
@using TW.Utility
@model MyBlog_Post_PostInfo
@Html.HiddenFor(x => x.ID)
@Html.AntiForgeryToken()
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>标题</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="Title" name="Title" required value="@Model.Title" maxlength="50" placeholder="请输入标题" class="col-xs-10 col-sm-3">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">摘要</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <textarea name="Summary"  style="width: 300px" maxlength="200">@Model.Summary</textarea>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">博文分类</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="CategoryId" name="CategoryId" ajax-url="/Admin/Post/GetPostCategory?value=@Model.CategoryId"></select>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">发布时间</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="PubDate" name="PubDate" date="true" value="@(Model.ID==Guid.Empty?DateTime.Now.ToString("yyyy-MM-dd HH:ss"):Model.PubDate?.ToString("yyyy-MM-dd HH:ss"))" placeholder="请输入发布时间" class="col-xs-10 col-sm-2">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">作者</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="Author" name="Author"  value="@Model.Author" maxlength="10" placeholder="请输入作者" class="col-xs-10 col-sm-1">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">来源</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="Source" name="Source"  value="@Model.Source" maxlength="20" placeholder="请输入来源" class="col-xs-10 col-sm-3">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">链接</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="Liinks" name="Liinks"  value="@Model.Liinks" maxlength="100" placeholder="请输入链接" class="col-xs-10 col-sm-2">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">封面图片</label>
    <div class="col-sm-9">
        <div class="clearfix">
            @if (!string.IsNullOrEmpty(Model.ImageUrl))
            {
                <img id="showSmallImg" src="@(ReadConfig.ReadAppSetting("ImageUploadUrl") + Model.ImageUrl)" title="封面图片" style="max-height: 200px; border: solid 1px #ccc; margin-bottom: 5px;" />
            }
            <input id="upimage" type="file">
            <input type="hidden" name="ImageUrl" id="ImageUrl" value="" data-imgwh="302*0" maxlength="200" />
            <span style="color: red">建议图片大小:302*178</span>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">封面图片(第三方地址)</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="ImgUrlLink" name="ImgUrlLink" value="@Model.ImgUrlLink" maxlength="200" placeholder="请输入第三方地址" class="col-xs-10 col-sm-2">
            <span style="color: red">温馨提示,图片地址优先使用本地图片</span>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">文章详情</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <script id="myEditor" type="text/plain" style="height: 260px; width: 90%">
                @Html.Raw(Model.Content)
            </script>
            <textarea style="display: none" id="Content" name="Content"></textarea>
        </div>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">是否运行评论</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="IsComment" name="IsComment" style="width: 50px">@Html.Raw(SelectListItemHelper.LoadBitOption(Model.IsComment, false))</select>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">是否推荐</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="IsSelect" name="IsSelect" style="width: 50px">@Html.Raw(SelectListItemHelper.LoadBitOption(Model.IsSelect, false))</select>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">seo关键字</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="SeoKey" name="SeoKey"  value="@Model.SeoKey" maxlength="100" placeholder="请输入seo关键字" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">seo描述</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="SeoDescrition" name="SeoDescrition"  value="@Model.SeoDescrition" maxlength="200" placeholder="请输入seo描述" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>

<script src="/Areas/Admin/js/Post/PostInfoDetail.js"></script>